### ISSUE TITLE
Is wget a useful tool in this context?

### ISSUE THREAD

**Issue by ccstone** [cngarrison/rbbedit#4]
cURL is available on all versions of macOS.

Wget is not.

Other UNIX distros I cannot say.

-Chris

**Comment by LucasLarson** [comment]
Do you know which versions of macOS – and presumably of Mac OS X, too – where Wget isn’t available. I wasn’t immediately able to find that.

**Comment by ccstone** [comment]
> Do you know which versions of macOS – and presumably of Mac OS X, too – where Wget isn’t available. I wasn’t immediately able to find that.

Hey Lucas,

Wget is not available by default on _any_ version of macOS.  You have to install it yourself.

I use MacPorts for this, but HomeBrew is viable as well – and of course you can `make` wget yourself if you're so inclined.

-Chris

**Comment by cngarrison** [comment]
I'm not sure why I gave one install example using `curl` and the other using `wget`, but it was probably to indicate "use whichever tool you prefer". So if your system doesn't have `wget` then use `curl`.

Thanks Chris, I wasn't aware that `wget` wasn't standard.

Lucas, download with `curl` instead; this (untested) command should work:

`curl -L -O rbbedit https://github.com/cngarrison/rbbedit/raw/master/rbbedit `

-cng
